language: node_js
node_js:
- node
addons:
  ssh_known_hosts: ssh.stanrogo.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_bab956e4e3b0_key -iv $encrypted_bab956e4e3b0_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
script:
- npm run generate
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -q $TRAVIS_BUILD_DIR/dist stanrogo@ssh.stanrogo.com:/home/stanrogo/public_html/stanrogo.com/test/
  on:
    branch: master
