language: node_js
node_js:
    - node
addons:
    ssh_known_hosts: 160.153.18.20
before_deploy:
    - openssl aes-256-cbc -K $encrypted_3e25346d5705_key -iv $encrypted_3e25346d5705_iv
        -in deploy_rsa.enc -out deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
script:
    - npm run generate
deploy:
    provider: script
    skip_cleanup: true
    script:
    on:
        branch: master
after_deploy:
    - rsync -r --delete-after -q $TRAVIS_BUILD_DIR/dist stanrogo@ssh.stanrogo.com:/home/stanrogo/public_html/stanrogo.com/test/
